### PR TITLE
Bug Fixes for v2.1

### LINKED ISSUE #149: [PE-D] Incorrect parameters are accepted by add command
Command: add
Bug: add command accepts incorrect input that will break the storage feature

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: chocomango/ped#8

### LINKED ISSUE #179: Timing format
Timing should be in 24-hour format. e.g. "0980" or "1199" should not be accepted.
image

### PR DESCRIPTION
**Pull request by weisiong24**
Bug issue to issue #179 and #149

### CODE REVIEW

**Comment by yeapcl** [comment]
Bugs have been fixed in my upcoming PR

File: src/main/java/seedu/command/AddCommand.java [hunk 1]
```diff
@@ -47,10 +47,35 @@ public void execute(UserList users, Ui ui, User nowUser/*, Storage storage*/) th
...
+                            if (timeEndHour < 0 || timeEndHour > 23) {
+                                timetable.remove(newEvent);
+                                throw new WhereGotTimeException("Invalid Hour! It should be within "
+                                        + "24-hour format. (0000-2359)");
+                            } else if (timeEndMin < 0 || timeEndMin > 59) {
+                                timetable.remove(newEvent);
+                                throw new WhereGotTimeException("Invalid minute! It should be within "
+                                        + "24-hour format. (0000-2359)");
+                            }
+
```
Comment (yeapcl) [inline src/main/java/seedu/command/AddCommand.java:78]: perhaps the logic can be further improved by checking for time validity first, and if it's valid, proceed to add event. In other words, the flow shouldn't be deleting the event only after realising the time is not valid. This results in duplicated code.

**Review by yeapcl — COMMENTED** [review]
logic needs improvement

File: src/main/java/seedu/command/AddCommand.java (hunk 1 above)
Comment (weisiong24) [reply src/main/java/seedu/command/AddCommand.java:78]: The logic is the same, E.g. if you check  for validity then add and you still have to take into consideration of what happens if is invalid , keep or delete. So, if you check for invalid and remove them (not adding them) , it would be the same.

Comment (weisiong24) [reply src/main/java/seedu/command/AddCommand.java:78]: its even better to check and do action to invalidity first as after you check for validity you would still need to add and then keep track of the invalid (error message)

Comment (yeapcl) [reply src/main/java/seedu/command/AddCommand.java:78]: If the time is not valid to begin with, it should be thrown immediately and request the user to re-enter with valid timings. i.e. the case where "check for validity then add" does not need to happen, as the program will throw an exception

Comment (weisiong24) [reply src/main/java/seedu/command/AddCommand.java:78]: by this logic,but the invalid would still be added after the error message is shown.

Comment (weisiong24) [reply src/main/java/seedu/command/AddCommand.java:78]: image
image

Comment (yeapcl) [reply src/main/java/seedu/command/AddCommand.java:78]: I believe that implementing a checkTimeValidity function with throwable in line 34 would have been suffice. The invalid times would not be added to the event when the program throws an exception.
image

Comment (weisiong24) [reply src/main/java/seedu/command/AddCommand.java:78]: Nevermind, got it to work based on your proposed logic. Will work on it. Meanwhile can merge this first? i will do another pr after this.

**Review by yeapcl — APPROVED** [review]
